name: release-build-native-macos

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '19.3.1.java11'
    - name: version
      run: java -version
    - name: install native-image
      run: gu install native-image
    - name: Build Native
      run: gradle buildNative -Pversion="${{ github.event.release.tag_name }}"
    - name: List
      run: ls -l bpmn-diff/build
    - name: Upload Native Image (MacOS)
      id: upload-native-image-macos
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./bpmn-diff/build/bpmn-diff-${{ github.event.release.tag_name }}-runner
        asset_name: bpmn-diff-${{ github.event.release.tag_name }}-macos
        asset_label: macos
        asset_content_type: application/octet-stream